export const ADD_INGREDIANT = 'ADD_INGREDIANT'
export const REMOVE_INGREDIANT = 'REMOVE_INGREDIANT'
export const INIT_INGREDIENTS = 'INIT_INGREDIENTS'
export const INIT_INGREDIENTS_FAILED = 'INIT_INGREDIENTS_FAILED'