export const ADD_INGREDIANT = 'ADD_INGREDIANT'
export const REMOVE_INGREDIANT = 'REMOVE_INGREDIANT'
export const INIT_INGREDIENTS = 'INIT_INGREDIENTS'
export const INIT_INGREDIENTS_FAILED = 'INIT_INGREDIENTS_FAILED'
export const BURGER_ORDER_SUCCESS = "BURGER_ORDER_SUCCESS"
export const BURGER_ORDER_FAIL = "BURGER_ORDER_FAIL"
export const BURGER_ORDER_INIT = "BURGER_ORDER_INIT"
export const SET_ORDER_LOADING = "SET_ORDER_LOADING"